name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Print NX environment variables
        run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
          echo "REF: ${{ github.ref }}"

      - name: Run, build, and test affected apps
        run: npx nx affected -t lint test build

      - name: Build and push docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -f apps/ev-frontend1/Dockerfile . -t ev-frontend1
          docker tag ev-frontend1 631248157752.dkr.ecr.us-east-1.amazonaws.com/ev-app/ev-frontend1:latest
          docker push 631248157752.dkr.ecr.us-east-1.amazonaws.com/ev-app/ev-frontend1:latest
